# Generated by Django 4.2.16 on 2024-10-18 10:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0002_product_is_deleted_product_upl_name_product_upl_uri_and_more",
        ),
        ("open_producten", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the field",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Short description of the field",
                        max_length=300,
                        verbose_name="Description",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bsn", "Bsn"),
                            ("checkbox", "Checkbox"),
                            ("Cosign", "Cosign"),
                            ("currency", "Currency"),
                            ("date", "Date"),
                            ("datetime", "Datetime"),
                            ("email", "Email"),
                            ("iban", "Iban"),
                            ("licenseplate", "License Plate"),
                            ("map", "Map"),
                            ("number", "Number"),
                            ("password", "Password"),
                            ("phoneNumber", "Phone Number"),
                            ("postcode", "Postcode"),
                            ("radio", "Radio"),
                            ("select", "Select"),
                            ("selectBoxes", "Select Boxes"),
                            ("signature", "Signature"),
                            ("textfield", "Textfield"),
                            ("time", "Time"),
                        ],
                        default="textfield",
                        help_text="The formio type of the field",
                        max_length=255,
                        verbose_name="Type",
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "choices",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        blank=True,
                        default=list,
                        help_text="The Choices that can be selected in the form",
                        null=True,
                        size=None,
                        verbose_name="Choices",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        help_text="The product type that this field is part of",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="products.product",
                        verbose_name="Product Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field",
                "verbose_name_plural": "Fields",
            },
        ),
    ]
